### ISSUE TITLE
anthropic function calling

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-hub#139]
![IMG_3163](https://github.com/MartialBE/one-api/assets/95951386/884a6355-1d40-44a9-a5a3-88a96e27f122)

https://docs.anthropic.com/claude/docs/tool-use

大佬，claude也支持function call了

**Comment by MartialBE** [comment]
不支持 stream...
为啥不弄好了再发版。现在主流的工具都是使用stream的...

**Comment by woodchen-ink** [comment]
haha, 文档我还没详细看, 还是测试版

**Comment by MartialBE** [comment]
这个先放放。等它stream也支持了 我在统一支持吧。不然还得判断。

（我也没官方API..只有aws的 还不支持
