### ISSUE TITLE
渠道密钥管理逻辑优化

### ISSUE THREAD

**Issue by KarlLee830** [MartialBE/one-hub#140]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

当前的密钥逻辑管理有些麻烦
如我手中有多个OpenAI的渠道，每个密钥单独写，这导致我的渠道页面非常混乱且不易管理
能否添加一个渠道自定义分组功能，同一分组内渠道的所有设置相同（如可用模型，模型映射关系等）
但密钥，优先级与权重不同。

**Comment by MartialBE** [comment]
你有什么好的例子吗(别人实现过的)？
或者有什么好的交互逻辑吗？
因为如果合并编辑了，但是单独的密钥/优先级/权重去哪里编辑。

**Comment by KarlLee830** [comment]
> 你有什么好的例子吗(别人实现过的)？ 或者有什么好的交互逻辑吗？ 因为如果合并编辑了，但是单独的密钥/优先级/权重去哪里编辑。

我的设想是：
1、一个渠道可以被设置到一个分组内，也可以是单独的。这样如果需要设置单独的支持模型或映射关系的话可以选择不并入分组；
2、分组内只同步模型、模型映射关系、测速模型、渠道API地址、用户组、代理地址等基础内容；
3、分组内的各个渠道仍需要单独自行设置密钥，ID等也是按照现有模式编排，优先级权重亦是如此。只是方便统一编辑；
4、分组更多的像是避免渠道管理页面过于混乱，且方便编辑，如我当前有多个渠道负载均衡，修改一下API地址等需要一个一个点进去修改，非常繁琐；

以下是我画的简单草图（非专业，仅作示意）
![image](https://github.com/MartialBE/one-api/assets/61072264/55c2e767-d20b-4e4e-a9dc-b3bb3cfa44db)

**Comment by MartialBE** [comment]
可以类似现在 模型价格一样 弄个tab页面。可以单条操作或者合并操作。

但是会有问题的是：
如果 某个分组中的渠道被单独编辑了模型/映射等其他设置，那么这时候在 编辑分组时，应该拿哪一条的数据取值。 会不会因为忘记了特殊编辑的渠道 导致在编辑分组时被全部覆盖了。

**Comment by KarlLee830** [comment]
> 可以类似现在 模型价格一样 弄个tab页面。可以单条操作或者合并操作。
> 
> 但是会有问题的是： 如果 某个分组中的渠道被单独编辑了模型/映射等其他设置，那么这时候在 编辑分组时，应该拿哪一条的数据取值。 会不会因为忘记了特殊编辑的渠道 导致在编辑分组时被全部覆盖了。

可以让被添加到分组的渠道的编辑页面，在前端直接将同步的模型等设置的内容改为不可编辑，变灰。

**Comment by KarlLee830** [comment]
如果是合并操作逻辑的话感觉可以加一个tag系统，可以直接一键修改同tag的部分内容。🤔

**Comment by MartialBE** [comment]
主要我不想破坏现在的表结构。
如果加上分组/tag的话 那么分页就用不了了。
所以我想拆成两个tab页。一个维持现有的逻辑。另一个只显示分组/tag的渠道列表，它会一次去读取所有打了分组/tag的渠道，然后来展示。

**Comment by MartialBE** [comment]
dev版本已支持。
`docker pull ghcr.io/martialbe/one-api:dev`
