### ISSUE TITLE
 无法请求Claude渠道模型  /v1/messages

### ISSUE THREAD

**Issue by 80imike** [MartialBE/one-hub#175]
nextchat 中报以下的错

<img width="550" alt="image" src="https://github.com/MartialBE/one-api/assets/1665201/0610c4f3-0198-40c7-b150-98eecd707214">

这个问题在 songquanpeng/one-api 上游中也是存在的

 https://github.com/songquanpeng/one-api/issues/1168 

大佬能不能修一修？

**Comment by MartialBE** [comment]
nextchat 会通过模型名称 来处理调用`api`， 你可以先通过把模型映射更改一下`claude`的模型名称 来解决这个问题。
要支持的话，要晚些。

**Comment by BigDataMao** [comment]
请您帮忙修复

**Comment by MartialBE** [comment]
已经支持Claude API调用了，但是需要在路径后面添加 /claude （仅Claude/vertex渠道支持）
完整请求路径： https://api.onehub.com/claude/v1/messages。

**Comment by imzhoukunqiang** [comment]
> 已经支持Claude API调用了，但是需要在路径后面添加 /claude （仅Claude/vertex渠道支持） 完整请求路径： [https://api.onehub.com/claude/v1/messages。](https://api.onehub.com/claude/v1/messages%E3%80%82)

你好，问什么要加一个路径呢，可以支持claude原生的路径吗

**Comment by MartialBE** [comment]
> > 已经支持Claude API调用了，但是需要在路径后面添加 /claude （仅Claude/vertex渠道支持） 完整请求路径： [https://api.onehub.com/claude/v1/messages。](https://api.onehub.com/claude/v1/messages%E3%80%82)
> 
> 你好，为什么要加一个路径呢，可以支持claude原生的路径吗

为了不影响OpenAI的请求路径，不会直接支持原生的路径， 加个路径不影响什么， 只不过是baseurl多个路径而已。
