### ISSUE TITLE
隐藏未配置的登陆渠道

### ISSUE THREAD

**Issue by rdself** [MartialBE/one-hub#228]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望能自动隐藏未配置的登陆渠道，比如邮箱/github/wechat等，能够避免让用户产生困惑，并保持页面的简洁。
感谢！

![截屏2024-05-25 22 20 22](https://github.com/MartialBE/one-api/assets/55005611/3ba00dc6-3461-46a7-907c-6f6d6de40a4d)

**Comment by MartialBE** [comment]
最新的代码已经解决这个问题了，还没发版。
