### ISSUE TITLE
在只有一个Playground的情况下隐藏选择模块

### ISSUE THREAD

**Issue by RogerProSelf** [MartialBE/one-hub#235]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

希望能在只有一个playground的情况下隐藏顶部的选择模块，增加页面简洁性，感谢！

![截屏2024-05-27 14 25 53](https://github.com/MartialBE/one-api/assets/55005611/e0c3dcbd-c6c4-4f17-8457-1df7247aa122)

**Comment by MartialBE** [comment]
因为是循环出来的， 不太想去再做一个 判断了。
不影响使用的话，暂时不会改。
如果有能力帮忙，也欢迎pr
