### ISSUE TITLE
自动将映射的模型加入到模型列表

### ISSUE THREAD

**Issue by RogerProSelf** [MartialBE/one-hub#236]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

目前在配置自定义模型映射后，还需要手动将映射后的模型输入到模型列表内，希望能够简化这个过程，也避免每次从供应商拉取新的模型时候覆盖了这项配置。

比如映射是这样的：
{
  "google-gemini": "gemini-1.5-pro-latest"
}
目前用户需要手动将google-gemini填入到模型列表，每次从gemini拉取模型列表后都需要手动重新填写，略微有点不必要。

感谢！

**Comment by ZeroDeng01** [comment]
如果删除或者变更映射会不会导致模型列表有脏数据?因为删除或者变更映射程序不好判断原有映射是什么，是否应该删除或者变更

**Comment by MartialBE** [comment]
如果要加 
映射模型 一定是会追加在 模型列表中的。
肯定是前端处理方便。 go处理太麻烦了。

**Comment by MartialBE** [comment]
新版支持
