### ISSUE TITLE
自定义的模型费率未生效？

### ISSUE THREAD

**Issue by Adsryen** [MartialBE/one-hub#287]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
---

自定义的映射模型的价格，然后在消费后，日志和余额，依然使用的是0.06刀的倍率，并没有使用自定义的模型价格
经测试，只是对于有映射的模型，如果不进行映射的话，直接使用原本的模型名称，费用计算就**没有问题**

---
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/51238895/acd543ff-579f-4cfb-a9b8-d0b7c68aade8)

**Comment by MartialBE** [comment]
计费是映射后的模型价格。所以这个没问题
