### ISSUE TITLE
加载apexcharts时一直会有 Maximum call stack size exceeded 的报错

### ISSUE THREAD

**Issue by HKoon** [MartialBE/one-hub#297]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
点击 分析 页签时，经常会有apexcharts.js  Maximum call stack size exceeded 的报错. 图表无法正常显示.

**复现步骤**
Railway 或 zeabur 部署
点击控制台 - 点击 分析 页签

**预期结果**
白屏或者图表显示不全

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/24382626/04838ab1-47ab-4d1c-a963-72248349c4f0)

**Comment by MartialBE** [comment]
我没遇到这个问题， 是 因为某个种类过多的原因吗？
如果可以，你把能复现的数据，（即这个页面API请求的数据内容） 处理后发附件给我吗

**Comment by HKoon** [comment]
> 我没遇到这个问题， 是 因为某个种类过多的原因吗？ 如果可以，你把能复现的数据，（即这个页面API请求的数据内容） 处理后发附件给我吗

我重新部署一个能复现这个问题的示例站给大佬你看一下吧

**Comment by MartialBE** [comment]
好的 部署好后 发我邮箱 mailto:buer@xiao5.info

明天我看看

**Comment by HKoon** [comment]
> 好的 部署好后 发我邮箱 [buer@xiao5.info](mailto:buer@xiao5.info)
> 
> 明天我看看

我已经通过邮箱发送给大佬你啦

**Comment by MartialBE** [comment]
咦 我没有收到。垃圾箱也没有

**Comment by HKoon** [comment]
访问网址：https://one-api-martial-production.up.railway.app
MySQL数据库连接：
Host: roundhouse.proxy.rlwy.net
Port:  17988
User: root
Password: ywWYNUbPEFxmcjMNkYoihdeTtQmwzftS
Database: railway

**Comment by HKoon** [comment]
我直接发在这吧

**Comment by MartialBE** [comment]
请拉取最新的代码 再部署一次

**Comment by HKoon** [comment]
已经重新部署好了

**Comment by MartialBE** [comment]
已经好了

**Comment by HKoon** [comment]
哦哦哦，看到啦，太牛了。能请教一下大佬是什么原因么？

**Comment by MartialBE** [comment]
apexcharts 版本兼容问题

**Comment by HKoon** [comment]
哦哦哦，我也看到更新Diff了，感谢大佬!

**Comment by HKoon** [comment]
必须请大佬喝杯咖啡了
