### ISSUE TITLE
cursor使用报错,求功能:模型映射的时候,返回的模型可以自定义 为映射的模型吗?

### ISSUE THREAD

**Issue by jqlts1** [MartialBE/one-hub#301]
在使用 cursor 这个 ai 编辑器的时候,添加自定义模型会报错,目前我推测可能是模型映射的问题
比如图中:
<img width="667" alt="image" src="https://github.com/user-attachments/assets/066c2e32-1f62-4ca5-a390-465903a50ad4">

比如我这个图中:
我把 gpt-3.5-turbo -> yi-large-rag,但是我请求 gpt-3.5-turbo 的时候,接口返回会返回  **yi-large-rag**...

这个会带来一些不便,比如有的时候,需要隐藏接口实际使用的模型 (比如我自己包装一个接口,或是起一个模型的名字 ) 但是别人在调用我这个接口,我就暴露了我的真实模型了

希望可以加一个开关,某个渠道返回的信息,就返回映射模型的信息!

**Comment by jqlts1** [comment]
<img width="585" alt="image" src="https://github.com/user-attachments/assets/7f58f15a-3833-469b-a8ef-87fb5e40d26f">

比如在opencat 就会这样,我输入的模型和最后输出的会暴漏我的真实模型,...

**Comment by MartialBE** [comment]
这个和OpenAI的映射是一样的。
将通用模型映射到版本模型，你请求OpenAI `gpt-3.5-turbo` 会给你返回`gpt-3.5-turbo-xxx`.
这个暂时不会改

**Comment by MartialBE** [comment]
....
不提倡这种欺骗用户的行为。 
目前我也没遇到因为返回模型名称不一致就报错的情况。
一般也不会去限制返回模型名称和请求模型不一致就报错的。 因为openai返回的模型名称也是不一致的🙃
