### ISSUE TITLE
vertexai报channel not implemented

### ISSUE THREAD

**Issue by qingfengmy** [MartialBE/one-hub#304]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我vertexai模型，提示channel not implemented
**复现步骤**
![70872e15b49dbad051c53441b150d860](https://github.com/user-attachments/assets/71454885-e5c3-4073-8535-06d83bbab728)

![165e4d2d838ebd1661267fb3a2ffc72b](https://github.com/user-attachments/assets/8b9817b0-19a2-4039-8c0f-6d404f33d6c0)

报错
headers: {
    'content-length': '139',
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 17 Jul 2024 11:34:33 GMT',
    'x-oneapi-request-id': '20240717193433900409367YHiew5wR'
  },
  request_id: undefined,
  error: {
    code: 'channel_error',
    message: 'channel not implemented (request id: 20240717193433900409367YHiew5wR)',
    type: 'one_hub_error'
  },
  code: 'channel_error',
  param: undefined,
  type: 'one_hub_error'
}
**预期结果**
希望正常使用

**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
用ChatCompletions

**Comment by qingfengmy** [comment]
用ChatCompletions
