### ISSUE TITLE
openai-node的语法如果不支持vertexai的怎么用

### ISSUE THREAD

**Issue by qingfengmy** [MartialBE/one-hub#306]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**
![fbf6c7d4407513ec7bfed7377adf3ddb](https://github.com/user-attachments/assets/f3b28150-dc6d-489c-8b64-75102a08030b)

这参数类型都不一样，我应该怎么写？而且vertexai还支持识别视频内容，open-ai都没有视频的type

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
说明这个项目不适合你项目的选型。
你首先要搞清楚这个项目是干什么用的。

**Comment by qingfengmy** [comment]
ok
