### ISSUE TITLE
最新的main分支 执行测试全部渠道 程序会异常退出

### ISSUE THREAD

**Issue by huzw1995** [MartialBE/one-hub#307]
在zeabur构建镜像并部署后 执行测试全部渠道 程序会异常退出并触发重启

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
最新的main分支 执行测试全部渠道程序会异常退出
**复现步骤**
执行测试全部渠道，程序异常报错退出
**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/1658a2be-9c47-45fe-ae28-54d27fff5d08)

**Comment by MartialBE** [comment]
已修复

**Comment by huzw1995** [comment]
> 已修复

确认已修复
