### ISSUE TITLE
平台 日志模块 输入 输出 title 貌似互相标注反了

### ISSUE THREAD

**Issue by mimo-x** [MartialBE/one-hub#308]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**相关截图**
<img width="155" alt="image" src="https://github.com/user-attachments/assets/46aa1738-116f-4276-94b1-481e9c1c6c34">

输入应该是输出
输出应该是输入

**Comment by MartialBE** [comment]
<img width="256" alt="image" src="https://github.com/user-attachments/assets/3679bbae-2695-468d-b9f8-f333bd91f853">
OpenAI 我测试了，没有错，还是某个渠道类型记错了？

**Comment by MartialBE** [comment]
如果还有问题 可以再开启。
