### ISSUE TITLE
请求添加siliconflow供应商

### ISSUE THREAD

**Issue by Adsryen** [MartialBE/one-hub#309]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
拜托了

https://docs.siliconflow.cn/docs/getting-started
https://docs.siliconflow.cn/reference/stabilityaistable-diffusion-3-medium_text-to-image-1

**应用场景**

**Comment by wangfeng35** [comment]
+1

**Comment by MartialBE** [comment]
他不是和openai格式一样吗？
直接用自定义渠道就好了。

**Comment by zaite** [comment]
siliconflow是模型集成供应商，自定义渠道自定义模型就可以实现了

**Comment by yanwen** [comment]
+1

**Comment by Yanyutin753** [comment]
rerank渠道没有

**Comment by MartialBE** [comment]
> /rerank渠道没有

好像现在rerank没有一个通用接受的API接口，所以没对接

**Comment by Yanyutin753** [comment]
可以借鉴一下new-api的代码哈哈哈哈哈，可以适配个硅基的嘛🥺

**Comment by k8scat** [comment]
可以使用这个项目接入 siliconflow 的 flux 到 one-hub 中：https://github.com/k8scat/flux-api

**Comment by MartialBE** [comment]
已添加
