### ISSUE TITLE
utools中的ChatGPT.好友插件，ai回复结束了还是会保持输出状态。

### ISSUE THREAD

**Issue by oiflippy** [MartialBE/one-hub#317]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
如题，utools中的ChatGPT.好友插件，ai回复结束了还是会保持输出状态。
**复现步骤**
输入服务器地址和密钥后，AI回复正常，但回复结束后，插件无法监测到对话已经结束，我知道可能是插件的问题，但是原版one api是正常结束的，我实验了本地one hub one api 云端one hub one api,结果都是one api没问题，one hub结束不了
**预期结果**
如题，AI回复结束后应该自动结束
**相关截图**
一直处于回复状态：
<img width="1235" alt="屏幕截图 2024-07-22 084029" src="https://github.com/user-attachments/assets/05273c91-7b43-432d-bbf6-c1846ada8137">

**Comment by MartialBE** [comment]
是所有渠道模型都这样。还是某些渠道类型的模型是这样？

**Comment by oiflippy** [comment]
> 是所有渠道模型都这样。还是某些渠道类型的模型是这样？

是所有渠道所有模型都会这样

**Comment by MartialBE** [comment]
已修复
