### ISSUE TITLE
手动点击*测试所有渠道*，失败的不会禁用吗？

### ISSUE THREAD

**Issue by Passerby1011** [MartialBE/one-hub#320]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
如题，我有一个渠道，可以肯定已经失效了单独测试它也是失败的，在点击*测试所有渠道*后不会自动禁用吗？
![image](https://github.com/user-attachments/assets/edbc2f40-e5eb-489f-aeaa-af3ed1b579b3)

**复现步骤**

**预期结果**
点击*测试所有渠道*后失效的渠道会自动禁用
**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
设置开启自动禁用了吗

**Comment by Passerby1011** [comment]
当然开启了

**Comment by MartialBE** [comment]
500 错误 不会被禁用
