### ISSUE TITLE
接口更新

### ISSUE THREAD

**Issue by wwdmy123** [MartialBE/one-hub#321]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
很多渠道模型已经支持联网检索了，但是这里还没有更新，希望大佬有时间了，可以看一下。比如海螺、零一万物这些。

**应用场景**
官方可以联网，但是调用api没有

**Comment by Hafoxk** [comment]
佬，希望添加是否开启web_search联网，质谱的glm-4-alltools模型目前无法调用工具

**Comment by MartialBE** [comment]
> 佬，希望添加是否开启web_search联网，质谱的glm-4-alltools模型目前无法调用工具

-。- ，这个鬼模型这么贵的吗，调试几下，我20大洋没了， 对接不起....

**Comment by Hafoxk** [comment]
> > 佬，希望添加是否开启web_search联网，质谱的glm-4-alltools模型目前无法调用工具
> 
> -。- ，这个鬼模型这么贵的吗，调试几下，我20大洋没了， 对接不起....

质谱这个模型确实有点贵，1毛1000tk,我可以给你提供key，你随意调试

**Comment by Hafoxk** [comment]
> > 佬，希望添加是否开启web_search联网，质谱的glm-4-alltools模型目前无法调用工具
> 
> -。- ，这个鬼模型这么贵的吗，调试几下，我20大洋没了， 对接不起....

加你企鹅了，同意一下，我给你发key

**Comment by MartialBE** [comment]
minimax 的插件调用的接口，和目前用的接口不一致，暂时没有精力去适配了。
01 好像只有RAG 检索，没有看到联网搜索。

**Comment by Panweitong** [comment]
智谱的glm-4-0520模型调用我自己弄的bing搜索函数时，函数可以执行返回结果，但是结果交给glm-4-0520模型后，返回结果：很抱歉，我无法直接调用Bing搜索工具或其他外部API来执行搜索。作为一个语言模型，我的功能仅限于处理和生成文本。如果您需要搜索人工智能案例，我建议您使用Bing搜索引擎或其他在线资源来获取相关信息。
