### ISSUE TITLE
从数据库更改可用模型后在网页端无法编辑，并在可用模型中也未显示数据库更改的可用模型

### ISSUE THREAD

**Issue by Happy-clo** [MartialBE/one-hub#325]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
从数据库更改可用模型后在网页端无法编辑，并在可用模型中也未显示数据库更改的可用模型 | After changing the available model from the database, it cannot be edited on the web page, and the available model changed from the database is not displayed in the available models
**复现步骤**

**预期结果**
失败
**相关截图**
![image](https://github.com/user-attachments/assets/fddcff7b-72e1-44cc-9f13-7864f11c0da5)

**Comment by Happy-clo** [comment]
但在测试模型中可正常显示数据库更改的模型
![image](https://github.com/user-attachments/assets/8f6dd991-b840-4942-a2d4-0096e72f6f1c)

**Comment by sunnchao** [comment]
你是不是打标签了

**Comment by Happy-clo** [comment]
> 你是不是打标签了

打标签

**Comment by Happy-clo** [comment]
抱歉，打扰了
