### ISSUE TITLE
feat: 完整自定义渠道调用地址

### ISSUE THREAD

**Issue by GrayXu** [MartialBE/one-hub#329]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

目前onehub只能提供版本号替换的功能，`输入后，会替换请求地址中的v1，例如：freeapi，则请求chat时会变成https://xxx.com/freeapi/chat/completions,如果需要禁用版本号，请输入 disable`。  

有一些平台有open ai兼容API，但调用URL需要完整修改，如商汤的是`api.sensenova.cn/v1/llm/chat-completions`

new-api上好像有对应支持，`自定义渠道，支持填入完整调用地址`。

**Comment by MartialBE** [comment]
已完善
