### ISSUE TITLE
令牌查询额度的问题

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-hub#330]
![image](https://github.com/user-attachments/assets/b1e4d084-c4d5-4e8b-ba36-94700ed8f815)
目前切换是在这里

1. 如果启用了, 那么就无法查询令牌的设置额度(有限);
2. 如果不启用, 当令牌额度设置为无限的时候, 查出来的额度是$99999965.76这样.

## 希望的效果

当令牌额度有限时, 查出来是令牌的额度.
当令牌额度无限时, 查出来是账户的额度.

**Comment by MartialBE** [comment]
删除了后台设置 `Billing 相关 API 显示令牌额度而非用户额度` 设置。
直接按照下面规则返回数据：
当令牌额度有限时, 查出来是令牌的额度.
当令牌额度无限时, 查出来是账户的额度.

**Comment by woodchen-ink** [comment]
TKS~
