### ISSUE TITLE
Gemini 识别图片问题

### ISSUE THREAD

**Issue by ikmfoundation** [MartialBE/one-hub#334]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [X] 我已确认目前没有类似 issue
+ [X] 我已确认我已升级到最新版本
+ [X] 我已完整查看过项目 README，尤其是常见问题部分
+ [X] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
根据截图，发送什么图片都是相同回答。都是说明413错误，请问是什么问题呢？试了newapi oneapi都没问题，但比较喜欢用你的ui版本。

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/0cecd58b-7178-48a6-93f3-1b6a1c960a61)

**Comment by MartialBE** [comment]
请给出日志报错信息

**Comment by ikmfoundation** [comment]
你好 自己找到原因了 可能代码不识别项目的某些逻辑，改了下项目代码就可以了。我直接关了哈，谢谢打扰了
