### ISSUE TITLE
sambanova-ai的逆行api无法进行测速

### ISSUE THREAD

**Issue by huawuhen** [MartialBE/one-hub#335]
sambanova-ai逆行后的api在AMA客户端测试正常，添加渠道测速报错 ` Provider API error: bad response status code 400 `
但是不影响使用，AMA客户端配置one-hub后照常可以使用sambanova-ai模型

**Comment by MartialBE** [comment]
是否你的逆向不支持非流式请求？ 不支持的话测试就会报错。

**Comment by GrayXu** [comment]
sambanova的api只支持stream调用，不管是逆向的还是fast_api
