### ISSUE TITLE
请问是否有token长度截断啊？

### ISSUE THREAD

**Issue by 3377** [MartialBE/one-hub#337]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我基于one-hub使用google的veltex的claude-3.5生成代码，代码量一大就老是需要我点击继续生成。在好几个客户端都会这样。在客户端我已经设置不限制上下文长度和token长度了，谷歌本身不限制，只能想到中转api的可能了？
求大佬帮忙解答，如果有，该如何解除。
比如这里，最后一个生成的就是我点击继续生成的结果。
![image](https://github.com/user-attachments/assets/4bfefaad-744d-4820-bcf4-c8463fa26e7b)

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
Claude 3.5 原本最大上下文就是4k。
8k上下文仅在官方API内测，one hub已经处理，会自动开启8k。
但是vertexAI不支持。

**Comment by 3377** [comment]
啊啊啊，我就说呢，一直好奇到底是哪里限制了，这个有办法解决吗。。。。

**Comment by MartialBE** [comment]
使用官方API

**Comment by 3377** [comment]
![image](https://github.com/user-attachments/assets/1e403767-b435-4de5-9f88-533ee96f1dc3)
官方不是说支持200k吗？

**Comment by MartialBE** [comment]
注意区别 上下文和最大输出

**Comment by MartialBE** [comment]
上下文是你输入最多可以给他这么多。最大输出是Claude最多给你回答这么多。

**Comment by MartialBE** [comment]
https://docs.anthropic.com/en/docs/about-claude/models#model-comparison-table

**Comment by 3377** [comment]
好的，感谢感谢解惑。

**Comment by MartialBE** [comment]
是的。说错了🤣

**Comment by 3377** [comment]
对了,deepseek也会这样，也是因为最大输出限制4K？
