### ISSUE TITLE
默认测试模型，像new-api 一样，默认选择第一个

### ISSUE THREAD

**Issue by candies404** [MartialBE/one-hub#338]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
 
默认测试模型，像new-api 一样，默认选择第一个模型测试

**应用场景**

**Comment by MartialBE** [comment]
万一第一个不是chat模型呢。不就失败了？
现在 你点击 响应时间 那里，测试的是你填写的测试模型， 测试按钮那里可以直接选择。

**Comment by 3377** [comment]
大佬，你是做前端的，能不能适配下手机端啊
