### ISSUE TITLE
github models无法使用

### ISSUE THREAD

**Issue by 3377** [MartialBE/one-hub#342]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
自定义渠道的方式，同样参数，new-api可行
![image](https://github.com/user-attachments/assets/9b1cff1c-88bd-400e-9703-2ccbb900ab43)
one-hub报错如下
![image](https://github.com/user-attachments/assets/3eaffbd5-3ed8-4780-93e6-b4cf78b08700)

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by ikmfoundation** [comment]
onehub也没问题 刚测了
API地址 https://models.inference.ai.azure.com
chatcompletions地址 /chat/completions

**Comment by 3377** [comment]
你这样不可能出的来的，one系列的要在最后加上#号才 行的。new-api才可以像你这么写。
感觉要换平台了。作者基本不更新了。。。哎

**Comment by ikmfoundation** [comment]
我就说了我刚刚测了
最新版本
不信就算了 :/

![image](https://github.com/user-attachments/assets/7f71675f-b1fc-426d-8af0-aed698c64b74)
![image](https://github.com/user-attachments/assets/d0792efc-01b8-43ee-bbb5-37e4217b615a)
![image](https://github.com/user-attachments/assets/4f2fc840-5247-4c79-a990-be2a6f1f1184)

**Comment by 3377** [comment]
这样是可以，你下面加了参数，你下面不加chatcompletions地址，直接在上面加个#也可以的

**Comment by 3377** [comment]
https://models.inference.ai.azure.com/chat/completions#
填这个

**Comment by ikmfoundation** [comment]
是啊 不就可以用 反正是用最新版本

**Comment by 3377** [comment]
常规方式是地址填这个：https://models.inference.ai.azure.com/chat/completions，如果没有特别说明谁知道后面需要加个#？

**Comment by MartialBE** [comment]
这是拼接url的问题，如果不填写下面的path，那么默认会有一个/v1的版本号，所以你要修改下面chat的path

**Comment by MartialBE** [comment]
> 常规方式是地址填这个：https://models.inference.ai.azure.com/chat/completions，如果没有特别说明谁知道后面需要加个#？

压根就不用加#，你加#相当于忽略了系统的拼接的地址了

**Comment by ikmfoundation** [comment]
加渠道的时候提示不都有注明清楚了
"你可以自定义每个请求的地址，空为默认值，disable为禁用该请求
默认为： /v1/chat/completions"

github的没有v1 就不能用默认的，自己加上对应请求path不就好了

**Comment by 3377** [comment]
不填chatcompletions的话，只填一行需要这样。不然的话会报错。
