### ISSUE TITLE
快速删除"有模型价格", 但是不属于"可用模型"的模型价格

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-hub#343]
标题有点绕~

实际情况是这样: 我的价格表都是直接拉的github上的这个价格.

然后呢, 很多模型我没有去配置渠道, 也就是说并没有办法使用. 

但是我通过模型价格API, 也就是这个接口:

![image](https://github.com/user-attachments/assets/5ed06c84-c742-4839-ba36-71f4a7cf2bf2)

返回的是"系统所有模型价格", 而不是只有"可用模型"的价格.

所以就很奇怪, 比如我的文档里:

![image](https://github.com/user-attachments/assets/4e28b9f4-d344-4e15-897e-455c57387b4a)

这些模型因为不好用, 国内还是先充钱后用的原因, 我都停掉了. 但是查价接口里还有.

有没有办法两个统一 一下?  

例如: 

1. 模型价格编辑处可以"清理无效价格"
![image](https://github.com/user-attachments/assets/2d08244b-6dd5-42e8-bf51-3b1ef3e91291)

2. 直接规范`/api/prices`接口, 只返回"可用模型"的价格

**Comment by MartialBE** [comment]
其实models那个接口返回的就是可用模型。 需要两个接口结合一下。 可以参考后台可用模型那个页面

**Comment by woodchen-ink** [comment]
> 其实models那个接口返回的就是可用模型。 需要两个接口结合一下。 可以参考后台可用模型那个页面

👌

**Comment by woodchen-ink** [comment]
额, model接口调用还需要key, 难道我建个0额度的key去调用接口? 😂

**Comment by woodchen-ink** [comment]
建了一个0.01额度的key, 调用成功了, 感觉好奇怪

**Comment by woodchen-ink** [comment]
大佬, 我让AI写了一个项目: https://github.com/woodchen-ink/Q58Bot

你能帮我看下代码结构和相关内容吗, 有没有错误和需要调整的地方😂

你是go后端大佬, 等有空闲着无聊的时候帮忙瞅一眼, 谢谢啦🙏

**Comment by woodchen-ink** [comment]
> 大佬, 我让AI写了一个项目: https://github.com/woodchen-ink/Q58Bot
> 
> 你能帮我看下代码结构和相关内容吗, 有没有错误和需要调整的地方😂
> 
> 你是go后端大佬, 等有空闲着无聊的时候帮忙瞅一眼, 谢谢啦🙏

好多库都是python原生有, go没有, 都是用的第三方库, go好惨🤣

**Comment by MartialBE** [comment]
> 接口调用还需要key, 难道我建个0额度的key去调用接口? 😂

是哦，这个接口要登录才可以。因为不同分组可能可用模型不一样，所以必须要登录。。。

如果你需要系统可用模型，你可以自己加一个接口，也很简单的

**Comment by woodchen-ink** [comment]
> > 接口调用还需要key, 难道我建个0额度的key去调用接口? 😂
> 
> 是哦，这个接口要登录才可以。因为不同分组可能可用模型不一样，所以必须要登录。。。
> 
> 如果你需要系统可用模型，你可以自己加一个接口，也很简单的

OKK
