### ISSUE TITLE
Claude 3 Opus 模型价格不正确

### ISSUE THREAD

**Issue by imbytecat** [MartialBE/one-hub#348]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
Claude 3 Opus 输出价格应为 `$0.075000/1k token`，倍率 37.5
**复现步骤**
https://github.com/MartialBE/one-hub/blob/7c8bfa9924cbb2ca36b9f70e0f4e2ef516c7c73b/prices.json#L350
**预期结果**
倍率 37.5

**Comment by MartialBE** [comment]
感谢。已修复
