### ISSUE TITLE
Stripe 支付設定

### ISSUE THREAD

**Issue by bentwnghk** [MartialBE/one-hub#371]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
Events 應該選什麼？選 Checkout 和 Payment Indent?
![Screenshot_20240928_083318_Chrome](https://github.com/user-attachments/assets/33798f78-5759-42e7-a00f-37055ca278c0)

Endpoint URL 应該填什麼？
![Screenshot_20240928_081142_Chrome](https://github.com/user-attachments/assets/ef4b400d-1d0f-4be8-bc1a-5ab9951c18a5)

**Comment by bentwnghk** [comment]
我 Endpoint URL 填上我的 domain URL，Stripe支付成功，但賬戶沒有成功充值! 日誌也沒有任何顯示。

**Comment by thlz998** [comment]
忘记给一个文档了，后边我做成自动创建的吧。
one-hub列表上有对应的uuid。
URL就是：https://xxxxxx.com/api/payment/notify/{uuid}

**Comment by bentwnghk** [comment]
Thank you! It's working now!
