### ISSUE TITLE
新的模型映射非常方便，但我还是建议保留原有的方式

### ISSUE THREAD

**Issue by igeekbb** [MartialBE/one-hub#372]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
 [ +] 我已确认目前没有类似 issue
 [ +] 我已确认我已升级到最新版本
 [+ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
 [+ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
 [+ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
新的模型映射设置对小白非常友好，+100,但对于有多个模型需要映射且多个渠道的映射设置一样，旧的映射方式只需要复制粘贴，新的得一个一个添加。建议保留原有的设置方式。
![CleanShot 2024-09-28 at 09 51 44@2x](https://github.com/user-attachments/assets/230ba115-2e34-4aa7-be46-f2d44994b3c0)

**应用场景**
多模型多渠道

**Comment by MartialBE** [comment]
后面加个切换按钮吧

**Comment by 3377** [comment]
我也有同样困惑，目前的方式非常好，但是建议提供一个一键复制的功能，不然新增渠道的时候比较麻烦，只能复制渠道去改其他参数。
