### ISSUE TITLE
支持链路/记录LLM输入&输出

### ISSUE THREAD

**Issue by an9xyz** [MartialBE/one-hub#374]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
目前对于链路追踪及LLM输入输出的记录是缺失的，可以抽象出集成接口（发送到opentelemetry/langfuse之类的可观测性服务）

**应用场景**

**Comment by MartialBE** [comment]
不会添加这个功能的
这个项目本身只是用于集中管理ai API，将各种不同格式的API转成openai格式，像链路/输入输出这些不属于这个项目做的事情。
