### ISSUE TITLE
腾讯混元 密钥 支持问题

### ISSUE THREAD

**Issue by pengshp** [MartialBE/one-hub#376]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
腾讯混元大模型的API调用支持两种方式
1. 按照如下格式输入：SecretId|SecretKey
2. 和OpenAI一样的单独密钥，sk-xxxxxxxxx

但是`腾讯混元`渠道里密钥只支持第一种方式，第二种更加普遍，希望增加支持，或者只支持第二种方式更加统一

**复现步骤**

**预期结果**
渠道里支持单密钥

**Comment by MartialBE** [comment]
他不是OpenAI格式吗？ 直接使用 自定义渠道 接入即可。
