### ISSUE TITLE
已有渠道的模型映射无法正删改查，整个呈现灰色

### ISSUE THREAD

**Issue by 3377** [MartialBE/one-hub#380]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
已有渠道的模型映射无法正删改查，整个呈现灰色。
新增渠道可以。
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/c1f16472-4c17-4d1b-865d-0331fc9d1da1)

如果没有的话，请删除此节。

**Comment by DrayChou** [comment]
整个模型列表也不能编辑。
好奇是特性还是 BUG。
私以为应该是允许修改才对。

**Comment by 2277419213** [comment]
以前是允许的，后面不知道出于什么考虑不允许的，还是请求可以修改

**Comment by MartialBE** [comment]
是不是填写了 标签。
把标签删了

**Comment by 2277419213** [comment]
> 是不是填写了 标签。 把标签删了

还真是，大哥牛

**Comment by DrayChou** [comment]
> 是不是填写了 标签。 把标签删了

唉？为什么填写了标签就不允许修改了？

**Comment by MartialBE** [comment]
这是用于批量管理的。 你添加后要去 渠道标签 修改
