### ISSUE TITLE
0.12.3 无法登陆

### ISSUE THREAD

**Issue by Hyominnnn** [MartialBE/one-hub#387]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用0.12.3版本无法登陆，登陆接口access_token返回为空
**复现步骤**
直接登录
**预期结果**
正常登录
**相关截图**
<img width="424" alt="image" src="https://github.com/user-attachments/assets/fdb4b196-3044-4dd7-a831-715038aa939c">

如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
先退回0.12.2版
正在排查

**Comment by MartialBE** [comment]
请尝试一下 v0.12.4
