### ISSUE TITLE
[体验优化]测速模型改为下拉选择框、模型名称点击复制

### ISSUE THREAD

**Issue by lazzman** [MartialBE/one-hub#391]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
1.渠道 - 编辑页面中，测试模型目前为文本输入框，建议改为下拉框
2.渠道 - 编辑页面中，点击模型复制名称

**应用场景**
![1](https://github.com/user-attachments/assets/779b7ff4-4294-4303-b45c-d843c826d698)

![2](https://github.com/user-attachments/assets/398c47cb-ca17-4aaa-8f92-7cb14e7bf6a7)

**Comment by 3377** [comment]
点击复制是个好想法，目前太脑残，得一个个手敲。
