### ISSUE TITLE
微信支付报错：“错误：创建支付失败，请稍后再试”

### ISSUE THREAD

**Issue by javastarboy** [MartialBE/one-hub#394]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
微信商户号以及应用都开通成功了，AppID、商户号、证书序列号、APIv3密钥、商户私钥都检查过了。
但是拉起支付后，就是报错“错误：创建支付失败，请稍后再试”， 容日日志后台也没有错误提示

**相关截图**
<img width="708" alt="3" src="https://github.com/user-attachments/assets/e18d6b3f-ecc2-4fb1-9607-751bb5afde75">
<img width="720" alt="2" src="https://github.com/user-attachments/assets/cb4a1963-bff3-497e-b659-4ca407ea3cab">
<img width="291" alt="1" src="https://github.com/user-attachments/assets/d50b9946-d580-4ca5-9b87-d3ab0a543d23">

**Comment by ZeroDeng01** [comment]
目前只集成了native方式不支持jsapi，并且需要正确填写v3证书等信息

**Comment by javastarboy** [comment]
我已经找到原因了，首次注册微信商户号，申请api证书时区分商户身份证书以及微信支付平台证书。
坑在平台证书这里，这个平台证书需要调用微信官方api下载，然后在微信商户号管理端才能看到这个证书。
没做从0-1过微信支付对接的开发者很难发现这个。

我的问题出在，使用的是商户身份证书，所以不行，应该通过api接口下载平台证书才行。

相关文档以及工具：
https://pay.weixin.qq.com/docs/merchant/apis/platform-certificate/api-v3-get-certificates/get.html
平台证书下载工具
https://pay.weixin.qq.com/docs/merchant/sdk-tools/platform-certificate-tool.html
https://github.com/wechatpay-apiv3/CertificateDownloader.git
证书查看：
https://myssl.com/cert_decode.html
https://kf.qq.com/faq/180824JvUZ3i180824YvMNJj.html

**Comment by yuansui486** [comment]
> 我已经找到原因了，首次注册微信商户号，申请api证书时区分商户身份证书以及微信支付平台证书。 坑在平台证书这里，这个平台证书需要调用微信官方api下载，然后在微信商户号管理端才能看到这个证书。 没做从0-1过微信支付对接的开发者很难发现这个。
> 
> 我的问题出在，使用的是商户身份证书，所以不行，应该通过api接口下载平台证书才行。
> 
> 相关文档以及工具： https://pay.weixin.qq.com/docs/merchant/apis/platform-certificate/api-v3-get-certificates/get.html 平台证书下载工具 https://pay.weixin.qq.com/docs/merchant/sdk-tools/platform-certificate-tool.html https://github.com/wechatpay-apiv3/CertificateDownloader.git 证书查看： https://myssl.com/cert_decode.html https://kf.qq.com/faq/180824JvUZ3i180824YvMNJj.html

老哥，我遇到了相同的问题，但是我依旧没明白如何配置，平台证书我也拿到了，编辑证书页面也没有放平台证书的地方啊
@javastarboy
