### ISSUE TITLE
匹配符号怎么使用，一个渠道里面有多个模型，我怎么去做匹配符号去匹配？希望有大佬些能解答一下，非常感谢

### ISSUE THREAD

**Issue by chiefluo** [MartialBE/one-hub#396]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
新增编辑渠道，模型 描述文字中有说明
