### ISSUE TITLE
用户分组只有default，vip和svip，不支持新增更多的分组和自定义

### ISSUE THREAD

**Issue by xuxu-ning** [MartialBE/one-hub#400]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
用户分组只有default，vip和svip，不支持新增更多的分组和自定义
**应用场景**
用户分组只有default，vip和svip，不支持新增更多的分组和自定义
因为我有多个渠道，但每个用户可用的渠道是要单独分开的，是否可以支持加更多的分组了？

**Comment by soulgod001** [comment]
在设置-倍率设置里面手动加

**Comment by MartialBE** [comment]
> 在设置-倍率设置里面手动加

最新版在 运营设置-用户分组 里面配置
