### ISSUE TITLE
gemini的流式输出里每一个data的finish_reason都是stop

### ISSUE THREAD

**Issue by GrayXu** [MartialBE/one-hub#402]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

gemini的流式输出里每一个data的finish_reason都是stop。正常应该是流式的最后一个data的finish_reason才是stop。  
这会导致一些软件无法正常输出。

搜了下看上去这是上游vertex/gemini就是这样的，不知道one-hub这层能不能做openai api style的适配？即最后一个data的finish_reason才是stop。

谢谢！

**Comment by MartialBE** [comment]
不行，我拿到数据就输出了，我不能知道哪一条是最后一条。

**Comment by GrayXu** [comment]
有道理🤣  
不知道全部置null会不会引入其他问题。不然只能晚回复一条消息来实现完全的匹配了。

**Comment by an9xyz** [comment]
> 不行，我拿到数据就输出了，我不能知道哪一条是最后一条。

https://github.com/MartialBE/one-hub/blob/3e677f1f635d0b28efbc19e9247eeeef559aed84/providers/gemini/type.go#L72

@MartialBE Gemini流式响应的`FinishReason`应该是写死了

**Comment by MartialBE** [comment]
> > 不行，我拿到数据就输出了，我不能知道哪一条是最后一条。
> 
> https://github.com/MartialBE/one-hub/blob/3e677f1f635d0b28efbc19e9247eeeef559aed84/providers/gemini/type.go#L72
> 
> @MartialBE Gemini流式响应的`FinishReason`应该是写死了

因为之前gemini 返回的全是stop，所以我就写死了。刚刚发现能正确返回了， 已经修复

**Comment by GrayXu** [comment]
@MartialBE  
感谢跟进这个issue。  
现在发现一个新的问题，就是`"finish_reason":"stop"`应该是出现在一个最后一个独立的带空content的data内。而现在的实现是最后一个带有效content的data内。  
一些app上会导致尾部截断（比如openai-translator）。
