### ISSUE TITLE
希望渠道优先级能够设置为负数，并且能配置为默认优先级排序而非ID排序

### ISSUE THREAD

**Issue by skywolf123** [MartialBE/one-hub#403]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
渠道优先级能够为负数很方便设置备用渠道，比如几十个渠道，只需将一个备用渠道设为负数。没有优先级为负的选择，就得将几十个渠道的优先级提升

**应用场景**

**Comment by MartialBE** [comment]
换个思路 优先级又没要求你一定要设置连续的数值，跳着设置不就好了么。 
优先级最高的我设置个50。 平均都来个20。这和能不能设置负数没有关系。
