### ISSUE TITLE
重试日志优化

### ISSUE THREAD

**Issue by lazzman** [MartialBE/one-hub#412]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
重试机制不太友好，要是能展示出重试记录就好了。比如chat-api中，就会在成功的日志中，展示重试的渠道ID集合。

**应用场景**

**Comment by lazzman** [comment]
chat-api的日志如图所示：
![image](https://github.com/user-attachments/assets/d220213a-f58b-4287-b2ef-318a7ea1d305)

**Comment by lazzman** [comment]
当然chat-api的方案也不是特别完美，如果超过重试次数，那么日志也是看不到哪些渠道失败的。
是不是可以添加一种日志类型？

**Comment by MartialBE** [comment]
重试不会计入日志，这个以后也不会做这个功能，本身这个就是无意义的日志，而记录日志是需要消耗数据库连接数的，那么请求量高的时候就会导致消耗大量性能。
针对这个问题，你可以搭建`prometheus/grafana`，在`grafana`查看重试的错误信息。
配置文件参考：https://gist.github.com/MartialBE/3738fcc1998464a3c090694afd31fb43

<img width="796" alt="image" src="https://github.com/user-attachments/assets/ddf0cff4-b30c-46b7-b6ba-54ec0ba52bcb">
