### ISSUE TITLE
优化新建模型价格时的选项，以放置不属于列表供应商的模型。

### ISSUE THREAD

**Issue by ningzimu** [MartialBE/one-hub#414]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
新建模型价格时，希望增加一个**自定义渠道**或者**其他渠道**的选项，以放置不属于列表供应商的模型。

比如新建渠道时，选择了**自定义渠道**，自定义渠道中存在一些自部署模型或者小众模型。目前只能将这些模型强制放在已支持的供应商里。

**复现步骤**
新建模型价格时

**预期结果**
对于自部署模型，或者小众厂商的模型，可以有一个类目存放，而不是强制放入已支持的供应商列表中。可以复用已有的渠道类型，比如自定义渠道。

相关问题：#389

**相关截图**
<img width="892" alt="image" src="https://github.com/user-attachments/assets/1d588318-b96a-4a39-ae0b-137f178750df">

<img width="475" alt="image" src="https://github.com/user-attachments/assets/57a0ab72-4dd1-4dc0-87c6-accf1f44dc19">
 

如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
已支持
