### ISSUE TITLE
AWS Bedrock渠道调用Claude 3.5 Sonnet v2失败

### ISSUE THREAD

**Issue by oudexin** [MartialBE/one-hub#415]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在使用Bedrock渠道调用Claude 3.5 Sonnet v2的时候，如果模型使用us.anthropic.claude-3-5-sonnet-20241022-v2:0提示出错原因：bedrock provider not found。

如果模型使用anthropic.claude-3-5-sonnet-20241022-v2:0或者claude-3-5-sonnet-20241022，则提示出错原因：Provider API error: Invocation of model ID anthropic.claude-3-5-sonnet-20241022-v2:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model.

是不是因为这个模型需要用Cross-Region Inference的原因？

**复现步骤**

**预期结果**

**相关截图**
请先喝杯咖啡
![WechatIMG73](https://github.com/user-attachments/assets/66db7e04-2926-4017-8a29-210809a55dde)

**Comment by ZeroDeng01** [comment]
升级最新版本配置![image](https://github.com/user-attachments/assets/b9504ec5-f6a2-41c9-95b3-547baf280c7c)

**Comment by oudexin** [comment]
> 升级最新版本配置![image](https://private-user-images.githubusercontent.com/19732560/387893272-b9504ec5-f6a2-41c9-95b3-547baf280c7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjczNTMsIm5iZiI6MTczMjA2NzA1MywicGF0aCI6Ii8xOTczMjU2MC8zODc4OTMyNzItYjk1MDRlYzUtZjZhMi00MWM5LTk1YjMtNTQ3YmFmMjgwYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAxNDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3OTcxNzM2NjE4ZjhkZGI4NjNkMWMwMmEzZDM2MjdhODg1N2E0YmQ1ZGUyMTZiYjk0MGU1MGQ1NThlMjRiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BaQf0TkNbbNfOC5b6Te2OAhjTdpn09OGeLJETxL9ADs)
> 
> > 是不是因为这个模型需要用Cross-Region Inference的原因？
> > AWS控制台标记Cross-Region Inference的就需要相关Cross-Region Inference配置才可以使用

感谢大佬回复，换成us-west-2结点就可以正常使用了，但例如us-east-1之类的就不行，这些结点看起来有专门的要求：
![WX20241120-094245](https://github.com/user-attachments/assets/5fb3fca9-ea96-4f3d-9c4c-c4ec377ef292)

**Comment by ZeroDeng01** [comment]
> > 升级最新版本配置![image](https://private-user-images.githubusercontent.com/19732560/387893272-b9504ec5-f6a2-41c9-95b3-547baf280c7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjczNTMsIm5iZiI6MTczMjA2NzA1MywicGF0aCI6Ii8xOTczMjU2MC8zODc4OTMyNzItYjk1MDRlYzUtZjZhMi00MWM5LTk1YjMtNTQ3YmFmMjgwYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAxNDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3OTcxNzM2NjE4ZjhkZGI4NjNkMWMwMmEzZDM2MjdhODg1N2E0YmQ1ZGUyMTZiYjk0MGU1MGQ1NThlMjRiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BaQf0TkNbbNfOC5b6Te2OAhjTdpn09OGeLJETxL9ADs)
> > > 是不是因为这个模型需要用Cross-Region Inference的原因？
> > > AWS控制台标记Cross-Region Inference的就需要相关Cross-Region Inference配置才可以使用
> 
> 感谢大佬回复，换成us-west-2结点就可以正常使用了，但例如us-east-1之类的就不行，这些结点看起来有专门的要求： ![WX20241120-094245](https://private-user-images.githubusercontent.com/8954608/387896267-5fb3fca9-ea96-4f3d-9c4c-c4ec377ef292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzM3MDgsIm5iZiI6MTczMjA3MzQwOCwicGF0aCI6Ii84OTU0NjA4LzM4Nzg5NjI2Ny01ZmIzZmNhOS1lYTk2LTRmM2QtOWM0Yy1jNGVjMzc3ZWYyOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMDMzMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzUwMmY3MDRjNTdhNDJlZWY3YmQ3YWU4YTE5MjQyMzNkODlkN2YyNjAzMzU4ZGIwOTI2MDE1YzEzZmEwNWEyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.z__kXX1iZVdl9fV9jMUw6OD6c-hOZin0QkJSsGZoo40)

是的  一些区域对应模型只能使用cross-region特定的id进行请求

**Comment by MartialBE** [comment]
对于还没更新的AWS映射的模型，可以直接填写完整的模型名称，然后在渠道中使用模型映射来解决。
