### ISSUE TITLE
免费模型记录日志失败

### ISSUE THREAD

**Issue by an9xyz** [MartialBE/one-hub#417]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

正常请求后日志列表中无记录，查看服务日志提示：
```
2024/11/21 - 18:41:59    ERROR    logger/logger.go:173    2024...YVKX | user_id: 1, channel_id: 4, token_id: 1, quota is 0                            
```
~version `v0.12.4`~ 最新版也有同样问题

**复现步骤**

**预期结果**
期望日志可以正确记录额度为0的请求记录

**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
已修复
