### ISSUE TITLE
/pricing的新建模型价格按钮无效

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-hub#420]
![image](https://github.com/user-attachments/assets/8f1140e2-2292-426c-a875-47234d9d7b07)

测下看看呢, 我本地和演示站都无效, 按钮没绑定事件好像

https://github.com/MartialBE/one-hub/blob/45f55dddef840dfe6ef03d661cccee5c18769d91/web/src/views/Pricing/index.jsx#L217

**Comment by MartialBE** [comment]
上次换图标的时候，cursor tab一路下去，估计把事件给删了🤣

**Comment by woodchen-ink** [comment]
> 上次换图标的时候，cursor tab一路下去，估计把事件给删了🤣

啊? 你也用cursor了吗?  好用不, 好像收费的.

**Comment by MartialBE** [comment]
> > 上次换图标的时候，cursor tab一路下去，估计把事件给删了🤣
> 
> 
> 
> 啊? 你也用cursor了吗?  好用不, 好像收费的.

好用，回不去了。 很方便。

**Comment by woodchen-ink** [comment]
> > > 上次换图标的时候，cursor tab一路下去，估计把事件给删了🤣
> > 
> > 
> > 啊? 你也用cursor了吗?  好用不, 好像收费的.
> 
> 好用，回不去了。 很方便。

真香
