### ISSUE TITLE
hashidsSalt 中的字符必须是唯一的，不能重复出现。

### ISSUE THREAD

**Issue by awwaawwa** [MartialBE/one-hub#422]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

使用具有重复字符的hashidsSalt会产生如下报错：[failed to initialize user token: alphabet must contain unique characters]。

**复现步骤**

使用任意具有重复字符的hashidsSalt作为环境变量HASHIDS_SALT，尝试运行docker，报错。

**预期结果**

修改wiki中环境变量一节，增加相关说明。

**相关截图**
![CleanShot 2024-11-30 at 19 16 27@2x](https://github.com/user-attachments/assets/55cf68f3-f701-49d5-9f47-45c630a12328)

**Comment by Silentely** [comment]
通过python去生成对应的字符串和盐
`import random
import string
from hashids import Hashids

def generate_random_string(length=32):
    characters = string.ascii_letters + string.digits
    random_string = ''.join(random.choice(characters) for _ in range(length))
    return random_string

# 生成32位随机字符串
random_string = generate_random_string()
print(f"32位随机字符串: {random_string}")

# 使用生成的32位随机字符串作为盐生成62位的hashids
salt = random_string
hashids = Hashids(salt=salt, min_length=62)

# 生成一个hashid，这里使用一个简单的数字作为示例
number = 12345
hashid = hashids.encode(number)

print(f"62位hashid: {hashid}")`

**Comment by awwaawwa** [comment]
您给出的python某版代码是 `hashids = Hashids(salt=salt, min_length=62)`，[本项目的go代码为](https://github.com/MartialBE/one-hub/blob/efe69b7855561780848254f9f7228c8279ea2429/common/user-token.go#L40C1-L41C1) `Alphabet:  hashidsSalt`。应该将python代码改为`hashids = Hashids(alphabet=salt, min_length=62)`才与本项目go代码对应。

进一步，该python库相关Hashids初始化代码节选如下。代码中可见`alphabet = ''.join(x for i, x in enumerate(alphabet) if alphabet.index(x) == i and x not in separators)`，这句话对alphabet做了去重操作。所以即使传递具有重复字符的alphabet，python库也不会报错，会正常执行。然而[squid go库](https://github.com/sqids/sqids-go/blob/2ba95c7920dcf08340e099c7b22beb1178da6106/sqids.go#L76C1-L79C3)中并不会做去重操作，而是在遇到有重复字符时直接报错。

```python
class Hashids(object):
    """Hashes and restores values using the "hashids" algorithm."""
    ALPHABET = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'

    def __init__(self, salt='', min_length=0, alphabet=ALPHABET):
        """
        Initializes a Hashids object with salt, minimum length, and alphabet.

        :param salt: A string influencing the generated hash ids.
        :param min_length: The minimum length for generated hashes
        :param alphabet: The characters to use for the generated hash ids.
        """
        self._min_length = max(int(min_length), 0)
        self._salt = salt

        separators = ''.join(x for x in 'cfhistuCFHISTU' if x in alphabet)
        alphabet = ''.join(x for i, x in enumerate(alphabet)
                           if alphabet.index(x) == i and x not in separators)
```

综上所述，您给出的生成salt代码会生成无效的alphabet。运行效果如图所示：

![CleanShot 2024-11-30 at 19 34 34@2x](https://github.com/user-attachments/assets/9169647f-00c6-462d-a2af-989d878cb3df)

**Comment by awwaawwa** [comment]
Sqids已经取消了salt参数，具体可参照：
[Sqids FAQ - 为什么取消了盐参数？](https://sqids.org/faq#salt)：
> The salt parameter was used to shuffle the alphabet, and it was never meant to be associated with security or safety. Both Hashids and Sqids work similarly to the way decimal to hexadecimal conversion works but with a few adjustments. There is no encryption of any kind, so to avoid confusion, that parameter has been removed completely.
> 盐值参数是用来对字母表进行洗码的，并不意味着它与安全或保安有关。Hashids 和 Sqids 的工作方式类似于十进制到十六进制 的转换，但有一些调整。由于不存在任何加密，为避免混淆，该参数已被完全删除。

[Sqids FAQ - What is Hashids?](https://sqids.org/faq#hashids)
> Hashids was the first version of this library that came out around 2013. It also produced short IDs but used a slightly different method.
> Hashids 是该库的第一个版本，于 2013 年左右问世。它也能生成简短的 ID，但使用的方法略有不同。

[Sqids FAQ - 为什么 Hashids 升级为 Sqids？](https://sqids.org/faq#hashids)
> Hashids handled a few things differently.
> 哈希德人的处理方式有些不同。
> It did not support a custom blocklist, but instead relied on the most common English profanity words. It also used the salt parameter to shuffle the alphabet which made it a little confusing because the library has nothing to do with encryption. Additionally, it used too many reserved characters which resulted in producing longer IDs.
> 它不支持自定义屏蔽列表，而是依赖于最常见的英语亵渎词。它还使用盐参数来洗字母表，这让人有点困惑，因为该库与加密无关。此外，它使用了太多的保留字，导致生成的 ID 较长。
> Therefore, we've decided to upgrade and rebrand. The algorithm has been simplified, a few features were added and the code repositories are all under [one roof now](https://github.com/sqids).
> 因此，我们决定进行升级和品牌重塑。我们简化了算法，增加了一些功能，并将代码库全部置于[统一管理之下](https://github.com/sqids)。

**Comment by Silentely** [comment]
修改为
```ruby
import secrets
import string

def generate_random_string(length=32):
    alphabet = string.ascii_letters + string.digits
    unique_chars = set()
    while len(unique_chars) < length:
        unique_chars.add(secrets.choice(alphabet))
    return ''.join(unique_chars)

user_token_secret = generate_random_string()
hashids_salt = generate_random_string()

print(f"user_token_secret: \"{user_token_secret}\"")
print(f"hashids_salt: \"{hashids_salt}\"")
```ruby

**Comment by MartialBE** [comment]
抱歉，我混淆了salt和alphabet的使用。
突然觉得这样好像把配置成本提高了。

**Comment by MartialBE** [comment]
修改了一下，允许 hashidsSalt为空，如果为空 则使用默认的alphabet表。并添加了说明文字

**Comment by mobilestack** [comment]
有个tip，如果遇到了类似的问题，删掉hashidsalt那行，如果docker compose文件配 .env文件的话，还得这么一句才管用，

`docker compose up -d --force-recreate one-hub`

而

`docker compose restart one-hub`

是不行的
