### ISSUE TITLE
自带的两个聊天功能都不能使用

### ISSUE THREAD

**Issue by sofs2005** [MartialBE/one-hub#434]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [* ] 我已确认目前没有类似 issue
+ [* ] 我已确认我已升级到最新版本
+ [* ] 我已完整查看过项目 README，尤其是常见问题部分
+ [* ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ *] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
自带的两个聊天功能都不能使用

**复现步骤**
无论选哪个模型都会报错：
chatgpt-web-midjourney-proxy报：
{
  "message": "fetch error, pleace check url",
  "url": "http://localhost:3000/v1/chat/completions",
  "code": "fetch_error"
}
ChatGPT Next报：
{
  "error": true,
  "message": "Failed to fetch"
}

**预期结果**

**Comment by MartialBE** [comment]
你应该有一个可以访问你服务的公开链接

**Comment by sofs2005** [comment]
> 你应该有一个可以访问你服务的公开链接

内网链接不行吗？一定要外网能访问的？

**Comment by MartialBE** [comment]
如果你自己部署这两个前端聊天在内网也是可以的。 
如果你要使用别人的服务调用你自己的内网不行，因为请求不到

**Comment by sofs2005** [comment]
> 如果你自己部署这两个前端聊天在内网也是可以的。 如果你要使用别人的服务调用你自己的内网不行，因为请求不到

用你这个软件肯定是自己部署好了呀，我其他软件内网调用都没问题，就你这两个不行用localhost和内网ip都是一样的错
