### ISSUE TITLE
谷歌gemini渠道对于openai格式的tool_calls存在字段丢失

### ISSUE THREAD

**Issue by paopaoandlingyia** [MartialBE/one-hub#436]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
谷歌gemini渠道下的模型在使用openai格式的tool_calls后，在后续对话中会丢失之前包含tool_calls字段那个json段中的content内容
**复现步骤**
使用apifox发送如下请求：
```
{
      "model": "gemini-1.5-flash-latest",
      "messages": [
        {
          "role": "system",
          "content": "你是一个绘图助手\n"
        },
        {
          "role": "user",
          "content": "请帮我画一只猫咪"
        },
        {
          "role": "assistant",
          "content": "好的，我正在绘图，请稍等",
          "tool_calls": [
            {
              "id": "call_fniPzIesUtg6P5pozp9myVT8",
              "type": "function",
              "function": {
                "name": "draw",
                "arguments": "{\"prompt\":\"Cute cat\"}"
              },
              "index": 0
            }
          ]
        },
        {
          "role": "tool",
          "content": "The drawing tool has been executed, the image has been generated successfully and has been sent to the user",
          "tool_call_id": "call_fniPzIesUtg6P5pozp9myVT8"
        },
        {
          "role": "assistant",
          "content": "我已经将图片发送给你"
        },
        {
          "role": "user",
          "content": "迄今为止你说过哪些话，排个序原封不动发给我"
        }
      ],
      "temperature": 1.1,
      "max_tokens": 4096
    }
    
```
使用gemini渠道的模型时返回结果会是：
```
"message": {
        "role": "assistant",
        "content": "1.我已经将图片发送给你\n"
      }
```

**预期结果**

```
 "message": {
         "role": "assistant",
         "content": "1. 好的，我正在绘图，请稍等\n2. 我已经将图片发送给你\n"
       }
```
**相关截图**
![image](https://github.com/user-attachments/assets/099b5e2b-6e3d-4c5e-90fb-be281c069747)
![image](https://github.com/user-attachments/assets/1c5cfbd4-11db-4f80-86f3-541d8a4fff50)

**Comment by MartialBE** [comment]
已修复。

**Comment by paopaoandlingyia** [comment]
> 已修复。

佬，我尝试拉取那个更新了，但是问题好像依然存在
![4cac586b9b09cac405f875ea7ecbdcfd](https://github.com/user-attachments/assets/97359283-1373-437f-97b3-3c6f2f559bee)
![5a2a439c3dba99b971f01594f57e224d](https://github.com/user-attachments/assets/636e1333-885c-4587-8be4-87dba08b7cf8)

**Comment by paopaoandlingyia** [comment]
> 已修复。

这里还有两张朋友发的截图
![1806bf8e4e9abf7ebcd441171b9c0003_720](https://github.com/user-attachments/assets/360ca1a2-6389-494b-8e6b-168e2ece7ff3)
![1d0387f621e206a3e8147f2d6b5f1af3](https://github.com/user-attachments/assets/b534d8d9-368e-4b2f-8b79-9be25108c25a)

**Comment by MartialBE** [comment]
我记得之前gemini在传递functincall 时是不能有content的。
不知道现在可以了嘛

**Comment by paopaoandlingyia** [comment]
应该可以的佬，我试过vertex的gemini模型（因为是openai渠道），是跟gpt一样可以的

**Comment by paopaoandlingyia** [comment]
我还试过把gemini放到自定义渠道里面，也是可以的

**Comment by MartialBE** [comment]
我晚点看看

**Comment by paopaoandlingyia** [comment]
好的好的，辛苦了
![image](https://github.com/user-attachments/assets/11bc2ce5-d18a-4f1f-97d1-89b8d8c24bb3)
这里是自定义渠道

**Comment by MartialBE** [comment]
再试试
