### ISSUE TITLE
AWS claude-3-5-sonnet-20241022

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-hub#439]
![image](https://github.com/user-attachments/assets/932434c6-b3ce-4b3d-b5f8-a91e13b7ce53)

AWS的claude-3-5-sonnet-20241022请求有问题

你的账号恢复了吗, 我突然发现我账号又能调用了

**Comment by woodchen-ink** [comment]
https://us-east-1.console.aws.amazon.com/bedrock/home?region=us-east-1#/model-catalog/serverless/anthropic.claude-3-5-sonnet-20241022-v2:0

**Comment by ZeroDeng01** [comment]
> ![image](https://github.com/user-attachments/assets/932434c6-b3ce-4b3d-b5f8-a91e13b7ce53)
> 
> 
> 
> AWS的claude-3-5-sonnet-20241022请求有问题
> 
> 
> 
> 你的账号恢复了吗, 我突然发现我账号又能调用了
> 
> 

我这边aws的请求正常呀

**Comment by woodchen-ink** [comment]
> claude-3-5-sonnet-20241022

![image](https://github.com/user-attachments/assets/fb6d1f46-7e38-4a3e-a464-67a633fea10a)
渠道模型是这样填吗

**Comment by ZeroDeng01** [comment]
> > claude-3-5-sonnet-20241022
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/fb6d1f46-7e38-4a3e-a464-67a633fea10a)
> 
> 渠道模型是这样填吗

是的，客户端填的这个

**Comment by woodchen-ink** [comment]
估计是账号问题
先关了
